project_id = "cxzywdzwbgeybpqssske"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.upload-document]
verify_jwt = false

[functions.share-documents]
verify_jwt = false
